fishtank/src/backend/docker.test.ts
fishtank/src/backend/docker.ts
fishtank/src/backend/index.ts

This commit adds a `Docker` class with a `runDetached` method that can spin up new containers in the background. Currently this method supports custom names and networks; in the future it may be extended to support more Docker features.

Add a minimal Docker backend that can start containers

---

fishtank/src/backend/docker.test.ts
fishtank/src/backend/docker.ts
fishtank/src/cluster.test.ts
fishtank/src/cluster.ts

Docker by default assigns random hostnames to containers (derived from the random container ID). This is an obstacle for cross-container communication. This commit changes the code that spawns new containers to set their host name to the node name, so that users can easily address other nodes.

Set predictable hostnames to spawned containers

---

fishtank/src/backend/docker.test.ts
fishtank/src/backend/docker.ts
fishtank/src/cluster.test.ts
fishtank/src/cluster.ts

This way, it is possible to unambiguously manage resources without the risk of interfering with existing Docker workloads. Labels may also be used in the future to identify resources that play a special role (e.g. bootstrap nodes vs regular nodes).
```
$ yarn start start abc
$ docker network inspect abc
...
"Labels": {
"fishtank.cluster": "abc"
}
...
$ yarn start spawn --cluster abc node-1
$ yarn start spawn --cluster abc node-2
$ docker inspect abc_node-1
...
"Labels": {
"fishtank.cluster": "abc"
}
...
$ yarn start stop abc
$ docker ps -a
$ docker network ls
```

Assign labels to Docker resources to mark them as part of a simulated cluster

---

fishtank-cli/src/commands/start.ts
fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/node.ts

A bootstrap node is automatically spawned when calling `init()` (unless this behavior is explicitly disabled).
All subsequently spawned nodes will be connected to the bootstrap node.

Spawn a bootstrap node when the cluster is initialized

---

fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/naming.ts
fishtank/src/node.ts

Naming of Docker resources is now delegated to a new `naming` module, which also performs validation.

Validate cluster and node names

---

fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/node.ts

Temporarily use new `NetworkDefinition` to unblock the dependency of https://github.com/iron-fish/ironfish/pull/4302
Remove cluster folder in teardown
@andiflabs

Allow spawning of nodes with custom network definitions

---

package.json

`@ironfish/sdk` was accidentally added to `devDependencies`. Move to `dependencies`

Make `@ironfish/sdk` a regular dependency

---

fishtank/src/cluster.test.ts
fishtank/src/cluster.ts

Pass options using `config.json` rather than using the command line. This allows for more flexibility, as well as type safety.

Pass all options via configuration values

---

fishtank-cli/src/commands/start.ts
fishtank/src/backend/docker.test.ts
fishtank/src/backend/docker.ts
fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/node.test.ts
fishtank/src/node.ts

The IPC interface has been replaced with TCP for better interoperability with non-Linux systems

Implement RPC communication on top of the TCP interface

---

fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/node.test.ts
fishtank/src/node.ts

This method is invoked automatically when a new node is spawned (and this behavior can be disabled)
Note that this PR may cause the simulator to crash with `Error: read ECONNRESET` in some circumstances. This is due to a bug in the Iron Fish SDK, which does not catch all errors from its client socket, and that in turn causes the entire Node.js process to crash in case an unhandled error occurs. The fix for this bug is in https://github.com/iron-fish/ironfish/pull/4317

Add a method to wait for nodes to start

---

package.json
yarn.lock

The latest SDK release contains a fix (259f052cd9e8f9ce1c379ed31d1d2b286795e9b2) that prevents crashes when connecting to a node's RPC too early after start.

Update `@ironfish/sdk` to 1.10.0

---

fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/node.test.ts
fishtank/src/node.ts

When a cluster is bootstrapped, at least 1 block is added on top of the genesis block, so that nodes can consider themselves as synced. This behavior can be disabled.
This also adds the `Node.mineUntil()` method to the simulator SDK, which will be extended further in future commits.
Start a new cluster:
```
yarn start start abc
```
Verify that the chain contains a least 2 blocks and that the status is `SYNCED`:
```
$ docker exec abc_bootstrap ironfish status
...
Blockchain           00000063c53685df3c21e298b4cf3c4d8bf283d075a79064000831e47135f27b (2), Since HEAD: 3s 346ms (SYNCED)
```

Mine 1 block when a cluster is bootstrapped

---

fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/node.test.ts
fishtank/src/node.ts

This way, the mining difficulty can be set to a number high enough that makes mining transactions possible.
This is a workaround to the preemptive block template generation that often privileges mining empty blocks, even if transactions are available in the mempool, effectively making it impossible in certain circumstances to mine any transaction. This workaround may be removed (in favor of using a standalone miner) once the preemptive block generation can be disabled.

Perform mining through a mining pool

---

fishtank/src/node.test.ts
fishtank/src/node.ts

This is made possible by calling `Node.mineUntil({ accountBalance: amount })`

Add functionality to mine blocks until a given amount of $IRON appears into the miner's account

---

package.json
scenarios/jest.config.js
scenarios/package.json
scenarios/src/index.ts
scenarios/src/mineTransaction.simulation.ts
scenarios/tsconfig.test.json

This simulation:
1. spins up two nodes
2. mines empty blocks on the first node until its default account has 2 $IRON
3. creates a transaction that sends 1 $IRON from the default account of the first node to the default account of the second node
4. mines blocks until the transaction is included in a block
5. verifies that the second node has received the 1 $IRON
The simulation is run as a Jest test in the `simulation` package.
Ensure that you have a working installation of Docker, then:
```
yarn simulate
```
Running a simulation may cause the following messages to be printed:
```
console.error
{"errno":-104,"code":"ECONNRESET","syscall":"read"}
```
These messages are printed whenever the code spins up a new node and tries to connect to its RPC interface right away, before the node has …

Add a simple simulation that makes a transfer

---

fishtank/src/cluster.ts

Also fixing a bug where the bootstrap options were not correctly being passed to `bootstrap()` from `init()`

Allow passing a custom `NetworkDefinition` on `bootstrap()`

---

fishtank/src/cluster.ts
scenarios/package.json

Simulations are very CPU-intensive and use multiple threads. Running multiple simulations at the same time can severely harm their performance.

Do not run simulations in parallel

---

fishtank/src/backend/docker.test.ts
fishtank/src/backend/docker.ts
fishtank/src/cluster.test.ts
fishtank/src/cluster.ts

On Linux, processes inside containers run as UID 0 (root) inside their UID namespace. As a result, files and directories created inside containers are owned by root. If the fishtank is not invoked as root, then it will fail to cleanup all files with a "permission denied" error.
This PR fixes the problem by invoking a container to clean up files, rather than trying to delete files directory. The cleanup container will be run with the same privileges as the containers that created those files, so it's guaranteed to succeed.
Note: this problem does not exist on macOS, because on macOS containers are run in a virtual machine, and Docker proxies the creation of files/directories on mounted volumes in a way that makes files/directories owned by the current user. This problem is specific to …

On teardown, remove files using a container

---

fishtank/src/cluster.test.ts
fishtank/src/cluster.ts

This forces the miners to mine transactions if the mempool is not empty. As a consequence, all simulations should become 100% reliable.

Disable preemptive block mining

---

fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/node.test.ts
fishtank/src/node.ts

Now that preemptive block mining is disabled, there's no longer the need to use a mining pool with a custom difficulty. A solo miner (with preemptive block mining disabled) can guarantee that pending transactions will be mined as soon as possible.

Revert back to using a solo miner

---

scenarios/src/hardFork1.simulation.ts
scenarios/src/index.ts

This simulation spins up two groups of nodes:
- one group that starts using v2 transactions after block 30
- another group that uses v1 transactions forever
The simulation than creates some transactions & mines blocks until after block 30. The simulation then verifies that blocks 1-29 are the same for both group of nodes, and blocks 30- are different between the two groups.

Add a simple simluation for hard fork 1

---

.github/workflows/run-scenarios.yml

Add a workflow which runs every midnight or can be triggered manually to run the test scenarios

feat(tank): Add CI job to run scenarios

---

fishtank/src/node.ts

When some code tries to connect to the RPC while the node is starting, the RPC client may print errors like this:
```
console.error
{"errno":-104,"code":"ECONNRESET","syscall":"read"}
at ConsoleReporter.logText (../node_modules/@ironfish/sdk/build/src/logger/reporters/console.js:53:65)
at ConsoleReporter.log (../node_modules/@ironfish/sdk/build/src/logger/reporters/text.js:109:14)
at _log (../node_modules/consola/dist/consola.js:1:8017)
at t (../node_modules/consola/dist/consola.js:1:7580)
at _logFn (../node_modules/consola/dist/consola.js:1:7970)
at _.<anonymous> (../node_modules/consola/dist/consola.js:1:6743)
at Socket.RpcSocketClient.onSocketError (../node_modules/@ironfish/sdk/build/src/rpc/clients/socketClient.js:131:25)
```
These errors are not a symptom of a bug, so they can be …

Suppress RPC connection error messages

---

fishtank/src/backend/docker.test.ts
fishtank/src/backend/docker.ts

After a recent update, I've seen that Docker has started to bind different ports for different IP stacks, which leads the `Node.connectRpc()` method sometimes try to connect to the port bound on the IPv6 stack, and apparently our RPC client does not support that, so that fails with an error. This updates the backend so that only ports bound to IPv4 addresses are considered.

When listing ports bound by Docker, collect only IPv4 addresses

---

scenarios/package.json

Simulations on GitHub Actions run with limited CPU cores, so much more time is needed for them.

Increase individual scenario timeout to 30 minutes

---

fishtank/src/cluster.ts
scenarios/jest.config.js
scenarios/src/setup.ts

This way it'll be easier to know at a glance what is being tested. This can be especially useful for GitHub CI runs.
Example output:
Configuration:
{
"defaultImage": "ironfish:latest",
"extraStartArgs": [],
"cleanup": true
}
Node version:
name       ironfish
version    1.12.0
git        src
runtime    node/20.9.0

Print simulations config and node version before each run

---

.github/workflows/ci.yml
.github/workflows/run-scenarios.yml
fishtank-cli/package.json
fishtank/package.json
fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/node.ts
package.json
scenarios/package.json
scenarios/src/hardFork1.simulation.ts
scenarios/src/index.ts
yarn.lock

- updated dependencies
- added `--experimental-vm-modules` to Node (required in Node 20.x)
- `networkId` is no longer supported in the configuration file; changed code to pass it on the command line instead
- changed serialization from `JSON` to `IJSON`

Update to Node 20.x and Iron Fish SDK 2.x

---

scenarios/src/assetOwnershipHardFork.simulation.ts

This hard fork didn't end up being the first hard fork, and it's also no longer scheduled, hence renaming.

Rename "hardFork1" to "assetOwnershipHardFork"

---

fishtank/src/cluster.test.ts
fishtank/src/cluster.ts
fishtank/src/node.test.ts

avoids permissions issues listening on IPC socket:
```
Error: listen EPERM: operation not permitted /root/.ironfish/ironfish.ipc
```
rpc connections use TCP instead of IPC in fishtank, so IPC does not need to be enabled by default

spawns nodes with IPC disabled by default
